[package]
name = "nigg-win32-kernel32"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc.workspace = true
log.workspace = true
parking_lot.workspace = true
nigg-ntapi = { path = "../ntapi" }
nigg-hlsl-compiler = { path = "../hlsl-compiler" }

[dev-dependencies]
tempfile = "3"
