[package]
name = "nigg-pe-loader"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
goblin.workspace = true
pelite.workspace = true
memmap2.workspace = true
libc.workspace = true
thiserror.workspace = true
log.workspace = true
env_logger.workspace = true
clap.workspace = true
nigg-runtime = { path = "../runtime" }
nigg-ntapi = { path = "../ntapi" }
nigg-win32-kernel32 = { path = "../win32-kernel32" }
nigg-win32-user32 = { path = "../win32-user32" }
nigg-win32-gdi32 = { path = "../win32-gdi32" }
nigg-d3d11-com = { path = "../d3d11-com" }
nigg-d3d12-com = { path = "../d3d12-com" }

[dev-dependencies]
nigg-tests-fixtures = { path = "../../tests/fixtures" }

[lib]
name = "nigg_pe_loader"

[[bin]]
name = "nigg-loader"
path = "src/bin/nigg-loader.rs"
